/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package faraz.view;

import faraz.error.*;
import java.sql.SQLException;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author FAM
 */
public class AdminView extends javax.swing.JFrame {

    /**
     * Creates new form AdminView
     */
    public AdminView() {
        initComponents();
        setTitle("Halaman Administrator - Admin Faraz Information System (FISt)");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        ImageIcon img = new ImageIcon("src/faraz/view/images/library.png");
        setIconImage(img.getImage());
        
        //Membuat tanggal
        Format formatter = new SimpleDateFormat("EEEE, dd MMMM yyyy");
        Date tanggal = new Date();
        String stanggal = formatter.format(tanggal);
        labelTanggal.setText(stanggal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelParent = new faraz.view.usu.Panel();
        toolbar = new faraz.view.usu.Toolbar();
        jLabel1 = new javax.swing.JLabel();
        btnDataBuku = new faraz.view.usu.Button();
        labelAdmin = new faraz.view.usu.Label();
        SeparatorMenu = new javax.swing.JSeparator();
        btnDataMember = new faraz.view.usu.Button();
        btnDataPenerbit = new faraz.view.usu.Button();
        btnDataPeminjaman = new faraz.view.usu.Button();
        DataPenjualan = new faraz.view.usu.Button();
        labePilihanMenu1 = new faraz.view.usu.Label();
        labelTanggal = new faraz.view.usu.Label();
        buttonPassword_admin = new faraz.view.usu.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelParent.setMaximumSize(new java.awt.Dimension(800, 600));
        panelParent.setPreferredSize(new java.awt.Dimension(800, 600));

        toolbar.setBackground(new java.awt.Color(50, 50, 50));
        toolbar.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Selamat Datang Admin Toko Buku Faraz");
        toolbar.add(jLabel1);

        btnDataBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/buku.png"))); // NOI18N
        btnDataBuku.setText("Data Buku");
        btnDataBuku.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDataBuku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDataBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataBukuActionPerformed(evt);
            }
        });

        labelAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelAdmin.setText("Anda login sebagai Admin Toko Buku Faraz");
        labelAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnDataMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/memberbaru.png"))); // NOI18N
        btnDataMember.setText("Data Member");
        btnDataMember.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDataMember.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDataMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataMemberActionPerformed(evt);
            }
        });

        btnDataPenerbit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/penerbit1.png"))); // NOI18N
        btnDataPenerbit.setText("Data Penerbit");
        btnDataPenerbit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDataPenerbit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDataPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataPenerbitActionPerformed(evt);
            }
        });

        btnDataPeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/peminjaman1.png"))); // NOI18N
        btnDataPeminjaman.setText("Data Peminjaman");
        btnDataPeminjaman.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDataPeminjaman.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDataPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataPeminjamanActionPerformed(evt);
            }
        });

        DataPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/penjualan.png"))); // NOI18N
        DataPenjualan.setText("Data Penjualan");
        DataPenjualan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DataPenjualan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DataPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataPenjualanActionPerformed(evt);
            }
        });

        labePilihanMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labePilihanMenu1.setText("Pilihan Menu");
        labePilihanMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        labelTanggal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTanggal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTanggal.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        buttonPassword_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/admin1.png"))); // NOI18N
        buttonPassword_admin.setText("Ganti Password");
        buttonPassword_admin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonPassword_admin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonPassword_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPassword_adminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelParentLayout = new javax.swing.GroupLayout(panelParent);
        panelParent.setLayout(panelParentLayout);
        panelParentLayout.setHorizontalGroup(
            panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelParentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelParentLayout.createSequentialGroup()
                        .addComponent(labelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelParentLayout.createSequentialGroup()
                                .addGap(0, 224, Short.MAX_VALUE)
                                .addGroup(panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SeparatorMenu)
                                    .addComponent(btnDataPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDataPenerbit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDataBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDataMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DataPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labePilihanMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(labelTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelParentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonPassword_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelParentLayout.setVerticalGroup(
            panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParentLayout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(labePilihanMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeparatorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDataBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDataMember, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDataPenerbit, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDataPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addComponent(DataPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(buttonPassword_admin, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelParent, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelParent, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDataPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataPenerbitActionPerformed
        // TODO add your handling code here:
        this.dispose();
        PenerbitView penerbit = new PenerbitView();
        try {
            penerbit.loadDatabase();
            penerbit.setVisible(true);
        } catch (PenerbitException ex) {
            Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDataPenerbitActionPerformed

    private void btnDataPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataPeminjamanActionPerformed
        // TODO add your handling code here:
        this.dispose();
        PinjamView pinjam = new PinjamView();
        try {
            pinjam.loadDatabase();
            pinjam.setVisible(true);
        } catch (PinjamException ex) {
            Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDataPeminjamanActionPerformed

    private void btnDataBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataBukuActionPerformed
        // TODO add your handling code here:
        this.dispose();
        BukuView buku = new BukuView();
        try {
            buku.loadDatabase();
            buku.setVisible(true);
        } catch (BukuException ex) {
            Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDataBukuActionPerformed

    private void btnDataMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataMemberActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MemberView member = new MemberView();
        try {
            member.loadDatabase();
            member.setVisible(true);
        } catch (MemberException ex) {
            Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDataMemberActionPerformed

    private void DataPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataPenjualanActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JualBeliView jualbeli = new JualBeliView();
        try {
            jualbeli.loadDatabase();
            jualbeli.setVisible(true);
        } catch (JualBeliException ex) {
            Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DataPenjualanActionPerformed

    private void buttonPassword_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPassword_adminActionPerformed
        // TODO add your handling code here:
        PasswordAdminView password = new PasswordAdminView(this, rootPaneCheckingEnabled);
        password.setVisible(true);
    }//GEN-LAST:event_buttonPassword_adminActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private faraz.view.usu.Button DataPenjualan;
    private javax.swing.JSeparator SeparatorMenu;
    private faraz.view.usu.Button btnDataBuku;
    private faraz.view.usu.Button btnDataMember;
    private faraz.view.usu.Button btnDataPeminjaman;
    private faraz.view.usu.Button btnDataPenerbit;
    private faraz.view.usu.Button buttonPassword_admin;
    private javax.swing.JLabel jLabel1;
    private faraz.view.usu.Label labePilihanMenu1;
    private faraz.view.usu.Label labelAdmin;
    private faraz.view.usu.Label labelTanggal;
    private faraz.view.usu.Panel panelParent;
    private faraz.view.usu.Toolbar toolbar;
    // End of variables declaration//GEN-END:variables
}
