/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package faraz.view;

import faraz.controller.MengelolaBuku;
import faraz.controller.MengelolaPenjualan;
import faraz.database.BukuDatabase;
import faraz.entity.Buku;
import faraz.error.BukuException;
import faraz.model.BukuModel;
import faraz.model.JualBeliModel;
import faraz.service.BukuDao;
import faraz.view.usu.TextBox;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FAM
 */
public class JualBeliKasirView extends javax.swing.JFrame {

    private JualBeliModel jualBeliModel;
    private MengelolaPenjualan jualBeliController;
    private BukuModel bukuModel;
    private MengelolaBuku bukuController;
    DefaultTableModel tableModel = new DefaultTableModel(
            new Object[][]{}, new String[]{"ID Buku", "Judul Buku", "Harga Jual", "Kuantitas", "Total"}) {

        @Override
        public boolean isCellEditable(int row, int column) {
            //all cells false
            return false;
        }
    };
    private int harga, kuantitas, total;

    /**
     * Creates new form JualBeliKasirView
     */
    public JualBeliKasirView() {

        jualBeliModel = new JualBeliModel();

        jualBeliController = new MengelolaPenjualan();
        jualBeliController.setModel(jualBeliModel);

        bukuModel = new BukuModel();

        bukuController = new MengelolaBuku();
        bukuController.setModel(bukuModel);

        initComponents();
        setTitle("Penjualan Buku - Faraz Information System (FISt)");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        ImageIcon img = new ImageIcon("src/faraz/view/images/library.png");
        setIconImage(img.getImage());

        tabelBuku.setModel(tableModel);
        tabelBuku.getTableHeader().setReorderingAllowed(false);
        tabelBuku.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 16));
        tabelBuku.getTableHeader().setBackground(Color.CYAN);
    }

    public TextBox getInputId_buku() {
        return inputId_buku;
    }

    public TextBox getInputId_member() {
        return inputId_member;
    }

    public TextBox getInputKuantitas() {
        return inputKuantitas;
    }

    public JTable getTabelBuku() {
        return tabelBuku;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelParent = new faraz.view.usu.Panel();
        toolbar = new faraz.view.usu.Toolbar();
        jLabel1 = new javax.swing.JLabel();
        panelMain1 = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        tabelBuku = new javax.swing.JTable();
        buttonHapus = new faraz.view.usu.Button();
        inputId_member = new faraz.view.usu.TextBox();
        labelId_member = new javax.swing.JLabel();
        labelId_buku = new javax.swing.JLabel();
        inputId_buku = new faraz.view.usu.TextBox();
        buttonReset = new faraz.view.usu.Button();
        buttonInsertJualBeli = new faraz.view.usu.Button();
        labelDenda2 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        buttonTambah = new faraz.view.usu.Button();
        buttonBatal = new faraz.view.usu.Button();
        labelKuantitas = new javax.swing.JLabel();
        inputKuantitas = new faraz.view.usu.TextBox();
        labelFokusId_MBK = new javax.swing.JLabel();
        buttonBack1 = new faraz.view.usu.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelParent.setMaximumSize(new java.awt.Dimension(800, 600));
        panelParent.setPreferredSize(new java.awt.Dimension(800, 600));

        toolbar.setBackground(new java.awt.Color(50, 50, 50));
        toolbar.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Penjualan Buku");
        toolbar.add(jLabel1);

        panelMain1.setBackground(new java.awt.Color(50, 50, 50));
        panelMain1.setMaximumSize(new java.awt.Dimension(1280, 800));

        tabelBuku.setBackground(new java.awt.Color(50, 50, 50));
        tabelBuku.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tabelBuku.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabelBuku.setForeground(new java.awt.Color(255, 255, 255));
        tabelBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane.setViewportView(tabelBuku);

        buttonHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/hapus2.png"))); // NOI18N
        buttonHapus.setText("Hapus");
        buttonHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        inputId_member.setBackground(new java.awt.Color(50, 50, 50));
        inputId_member.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputId_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputId_memberActionPerformed(evt);
            }
        });
        inputId_member.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputId_memberFocusGained(evt);
            }
        });
        inputId_member.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputId_memberKeyPressed(evt);
            }
        });

        labelId_member.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelId_member.setForeground(new java.awt.Color(255, 255, 255));
        labelId_member.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelId_member.setText("ID Member :");

        labelId_buku.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelId_buku.setForeground(new java.awt.Color(255, 255, 255));
        labelId_buku.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelId_buku.setText("ID Buku :");

        inputId_buku.setBackground(new java.awt.Color(50, 50, 50));
        inputId_buku.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputId_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputId_bukuActionPerformed(evt);
            }
        });
        inputId_buku.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputId_bukuFocusGained(evt);
            }
        });
        inputId_buku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputId_bukuKeyPressed(evt);
            }
        });

        buttonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/reset.png"))); // NOI18N
        buttonReset.setText("Reset");
        buttonReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        buttonInsertJualBeli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/simpan.png"))); // NOI18N
        buttonInsertJualBeli.setText("Simpan");
        buttonInsertJualBeli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonInsertJualBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertJualBeliActionPerformed(evt);
            }
        });

        labelDenda2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDenda2.setForeground(new java.awt.Color(255, 255, 255));
        labelDenda2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDenda2.setText(" Grand Total :");

        labelTotal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelTotal.setForeground(new java.awt.Color(255, 255, 255));
        labelTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTotal.setText("0");

        buttonTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/tambah.png"))); // NOI18N
        buttonTambah.setText("Tambah");
        buttonTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        buttonBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/batal.png"))); // NOI18N
        buttonBatal.setText("Batal");
        buttonBatal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        labelKuantitas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelKuantitas.setForeground(new java.awt.Color(255, 255, 255));
        labelKuantitas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelKuantitas.setText("Kuantitas :");

        inputKuantitas.setBackground(new java.awt.Color(50, 50, 50));
        inputKuantitas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputKuantitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKuantitasActionPerformed(evt);
            }
        });
        inputKuantitas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputKuantitasFocusGained(evt);
            }
        });

        labelFokusId_MBK.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelFokusId_MBK.setForeground(new java.awt.Color(255, 255, 255));
        labelFokusId_MBK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelFokusId_MBK.setText("<html>Masukkan digit jumlah buku yang dibeli untuk masing-masing buku, minimal pembelian 1</html>");

        buttonBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/kembali.png"))); // NOI18N
        buttonBack1.setText("Kembali");
        buttonBack1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMain1Layout = new javax.swing.GroupLayout(panelMain1);
        panelMain1.setLayout(panelMain1Layout);
        panelMain1Layout.setHorizontalGroup(
            panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMain1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMain1Layout.createSequentialGroup()
                        .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelMain1Layout.createSequentialGroup()
                                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelId_buku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelId_member, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelKuantitas, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputId_buku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputId_member, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputKuantitas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelFokusId_MBK, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMain1Layout.createSequentialGroup()
                                .addComponent(buttonBack1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(155, 155, 155))
                            .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMain1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(buttonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(80, 80, 80)
                                .addComponent(buttonBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonInsertJualBeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelMain1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane))))
                    .addGroup(panelMain1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelDenda2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelMain1Layout.setVerticalGroup(
            panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMain1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMain1Layout.createSequentialGroup()
                        .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTotal)
                            .addComponent(labelDenda2))
                        .addGap(22, 22, 22)
                        .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(buttonInsertJualBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonBack1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelMain1Layout.createSequentialGroup()
                        .addComponent(labelFokusId_MBK, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelId_member)
                            .addComponent(inputId_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelId_buku)
                            .addComponent(inputId_buku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelKuantitas)
                            .addComponent(inputKuantitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelParentLayout = new javax.swing.GroupLayout(panelParent);
        panelParent.setLayout(panelParentLayout);
        panelParentLayout.setHorizontalGroup(
            panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelParentLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panelMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        panelParentLayout.setVerticalGroup(
            panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParentLayout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelParent, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        if (tabelBuku.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Pilih dahulu baris yang akan dihapus");
        }
        int[] rows = tabelBuku.getSelectedRows();
        for (int i = 0; i < rows.length; i++) {
            tableModel.removeRow(rows[i] - i);
        }
        total = harga = kuantitas = 0;
        for (int i = 0; i < tabelBuku.getRowCount(); i++) {
            total += (Integer) tabelBuku.getValueAt(i, 4);
            labelTotal.setText(Integer.toString(total));
        }
        if (tabelBuku.getRowCount() == 0) {
            labelTotal.setText("0");
        }
        inisialisasi_tabel();
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void inputId_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputId_memberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputId_memberActionPerformed

    private void inputId_memberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputId_memberKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            inputId_buku.requestFocus();
        }
    }//GEN-LAST:event_inputId_memberKeyPressed

    private void inputId_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputId_bukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputId_bukuActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        // TODO add your handling code here:
        inputId_member.setText("");
        for (int i = tabelBuku.getRowCount() - 1; i >= 0; i--) {
            total -= (Integer) tabelBuku.getValueAt(i, 2);
            tableModel.removeRow(i);
        }
        inisialisasi_tabel();
        labelTotal.setText("0");
    }//GEN-LAST:event_buttonResetActionPerformed

    private void buttonInsertJualBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertJualBeliActionPerformed
        // TODO add your handling code here:
        if (jualBeliController.insertJualBeliKasir(this) == true) {
            bukuController.updateJualBeliBukuKasir(this);
            JOptionPane.showMessageDialog(this, "Transaksi penjualan berhasil");
        }
        else {
            JOptionPane.showMessageDialog(this, "Transaksi penjualan gagal");
        }
    }//GEN-LAST:event_buttonInsertJualBeliActionPerformed

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
        Buku buku = new Buku();
        buku.setId_buku(inputId_buku.getText());
        try {
            BukuDao dao = BukuDatabase.getBukuDao();
            try {
                buku = dao.getBuku(inputId_buku.getText());
                int k = (Integer) Integer.parseInt(inputKuantitas.getText());
                int totalnya = buku.getHarga_jual()*k;
                tableModel.addRow(new Object[]{
                            inputId_buku.getText(),
                            buku.getJudul_buku(),
                            buku.getHarga_jual(),
                            inputKuantitas.getText(),
                            totalnya
                        });
                inisialisasi_tabel();
                inputId_buku.setText("");
                inputKuantitas.setText("");
                total = 0;
                for (int i = 0; i < tabelBuku.getRowCount(); i++) {
                    total += (Integer) tabelBuku.getValueAt(i, 4);
                    labelTotal.setText(Integer.toString(total));
                }
            } catch (BukuException ex) {
                Logger.getLogger(PinjamKasirView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PinjamKasirView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void inputKuantitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKuantitasActionPerformed
        // TODO add your handling code here:
        buttonTambahActionPerformed(evt);
    }//GEN-LAST:event_inputKuantitasActionPerformed

    private void inputId_bukuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputId_bukuKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            inputKuantitas.requestFocus();
        }
    }//GEN-LAST:event_inputId_bukuKeyPressed

    private void inputId_memberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputId_memberFocusGained
        // TODO add your handling code here:
        labelFokusId_MBK.setText("<html>Jika pembeli buku bukan member, masukkan ID Member nya 'nonmember' (tanpa kutip)</html>");
    }//GEN-LAST:event_inputId_memberFocusGained

    private void inputId_bukuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputId_bukuFocusGained
        // TODO add your handling code here:
        labelFokusId_MBK.setText("<html>Masukkan ID Buku sesuai dengan buku yang dibeli</html>");
    }//GEN-LAST:event_inputId_bukuFocusGained

    private void inputKuantitasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputKuantitasFocusGained
        // TODO add your handling code here:
        labelFokusId_MBK.setText("<html>Masukkan digit jumlah buku yang dibeli untuk masing-masing buku, minimal pembelian 1</html>");
    }//GEN-LAST:event_inputKuantitasFocusGained

    private void buttonBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBack1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonBack1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private faraz.view.usu.Button buttonBack1;
    private faraz.view.usu.Button buttonBatal;
    private faraz.view.usu.Button buttonHapus;
    private faraz.view.usu.Button buttonInsertJualBeli;
    private faraz.view.usu.Button buttonReset;
    private faraz.view.usu.Button buttonTambah;
    private faraz.view.usu.TextBox inputId_buku;
    private faraz.view.usu.TextBox inputId_member;
    private faraz.view.usu.TextBox inputKuantitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel labelDenda2;
    private javax.swing.JLabel labelFokusId_MBK;
    private javax.swing.JLabel labelId_buku;
    private javax.swing.JLabel labelId_member;
    private javax.swing.JLabel labelKuantitas;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JPanel panelMain1;
    private faraz.view.usu.Panel panelParent;
    private javax.swing.JTable tabelBuku;
    private faraz.view.usu.Toolbar toolbar;
    // End of variables declaration//GEN-END:variables

    public void inisialisasi_tabel() {
        tabelBuku.setModel(tableModel);
    }
}
