/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package faraz.view;

import faraz.controller.MengelolaMember;
import faraz.database.MemberDatabase;
import faraz.entity.Member;
import faraz.error.*;
import faraz.model.MemberModel;
import faraz.model.TableMemberModel;
import faraz.model.event.MemberListener;
import faraz.service.MemberDao;
import faraz.view.usu.TextBox;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author FAM
 */
public class MemberView extends javax.swing.JFrame implements MemberListener, ListSelectionListener {

    private TableMemberModel tableModel;
    private MemberModel model;
    private MengelolaMember controller;
    
    JasperReport jasperReport;
    JasperDesign jasperDesign;
    JasperPrint jasperPrint;
    Map<String, String> param = new HashMap<String, String>();
    MemberDatabase koneksi = new MemberDatabase();

    /**
     * Creates new form MemberView2
     */
    public MemberView() {
        tableModel = new TableMemberModel();

        model = new MemberModel();
        model.setListener(this);

        controller = new MengelolaMember();
        controller.setModel(model);

        initComponents();
        setTitle("Data Member - Admin Faraz Information System (FISt)");
        setExtendedState(MAXIMIZED_BOTH);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ImageIcon img = new ImageIcon("src/faraz/view/images/library.png");
        setIconImage(img.getImage());

        tabelMember.getSelectionModel().addListSelectionListener(this);
        tabelMember.setModel(tableModel);
        tabelMember.getTableHeader().setReorderingAllowed(false);
        tabelMember.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 14));
        tabelMember.getTableHeader().setBackground(Color.CYAN);
    }

    public JTable getTabelMember() {
        return tabelMember;
    }

    public TextBox getInputAlamat() {
        return inputAlamat;
    }

    public TextBox getInputEmail() {
        return inputEmail;
    }

    public TextBox getInputId_member() {
        return inputId_member;
    }

    public TextBox getInputNama() {
        return inputNama;
    }

    public TextBox getInputTelepon() {
        return inputTelepon;
    }

    public JFormattedTextField getInputTanggal_member() {
        return inputTanggal_member;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelParent = new faraz.view.usu.Panel();
        panelMain1 = new javax.swing.JPanel();
        labelKodeMember = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tabelMember = new javax.swing.JTable();
        inputId_member = new faraz.view.usu.TextBox();
        buttonInsertMember = new faraz.view.usu.Button();
        buttonUpdateMember = new faraz.view.usu.Button();
        buttonDeleteMember = new faraz.view.usu.Button();
        labelNama = new javax.swing.JLabel();
        inputNama = new faraz.view.usu.TextBox();
        inputAlamat = new faraz.view.usu.TextBox();
        labelAlamat = new javax.swing.JLabel();
        labelTelepon = new javax.swing.JLabel();
        inputTelepon = new faraz.view.usu.TextBox();
        labelEmail = new javax.swing.JLabel();
        inputEmail = new faraz.view.usu.TextBox();
        buttonReset = new faraz.view.usu.Button();
        inputTanggal_member = new javax.swing.JFormattedTextField();
        labelFokusEmail = new javax.swing.JLabel();
        labelFokusTelepon = new javax.swing.JLabel();
        labelFokusId_member = new javax.swing.JLabel();
        buttonLaporan = new faraz.view.usu.Button();
        buttonBack1 = new faraz.view.usu.Button();
        toolbar = new faraz.view.usu.Toolbar();
        buttonBerandaView = new faraz.view.usu.Button();
        jLabel4 = new javax.swing.JLabel();
        buttonPenerbitView = new faraz.view.usu.Button();
        jLabel6 = new javax.swing.JLabel();
        buttonBukuView = new faraz.view.usu.Button();
        jLabel5 = new javax.swing.JLabel();
        buttonPinjamView = new faraz.view.usu.Button();
        jLabel7 = new javax.swing.JLabel();
        buttonJualBeliView = new faraz.view.usu.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelParent.setMaximumSize(new java.awt.Dimension(800, 600));
        panelParent.setPreferredSize(new java.awt.Dimension(800, 600));

        panelMain1.setBackground(new java.awt.Color(50, 50, 50));

        labelKodeMember.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelKodeMember.setForeground(new java.awt.Color(255, 255, 255));
        labelKodeMember.setText("ID Member :");

        tabelMember.setBackground(new java.awt.Color(50, 50, 50));
        tabelMember.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tabelMember.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tabelMember.setForeground(new java.awt.Color(255, 255, 255));
        tabelMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane.setViewportView(tabelMember);

        inputId_member.setBackground(new java.awt.Color(50, 50, 50));
        inputId_member.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputId_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputId_memberActionPerformed(evt);
            }
        });
        inputId_member.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputId_memberFocusGained(evt);
            }
        });

        buttonInsertMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/tambah.png"))); // NOI18N
        buttonInsertMember.setText("Tambah");
        buttonInsertMember.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonInsertMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertMemberActionPerformed(evt);
            }
        });

        buttonUpdateMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/update.png"))); // NOI18N
        buttonUpdateMember.setText("Update");
        buttonUpdateMember.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonUpdateMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateMemberActionPerformed(evt);
            }
        });

        buttonDeleteMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/hapus.png"))); // NOI18N
        buttonDeleteMember.setText("Hapus");
        buttonDeleteMember.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonDeleteMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteMemberActionPerformed(evt);
            }
        });

        labelNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNama.setForeground(new java.awt.Color(255, 255, 255));
        labelNama.setText("Nama :");

        inputNama.setBackground(new java.awt.Color(50, 50, 50));
        inputNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaActionPerformed(evt);
            }
        });
        inputNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNamaFocusGained(evt);
            }
        });

        inputAlamat.setBackground(new java.awt.Color(50, 50, 50));
        inputAlamat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAlamatActionPerformed(evt);
            }
        });
        inputAlamat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputAlamatFocusGained(evt);
            }
        });

        labelAlamat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelAlamat.setForeground(new java.awt.Color(255, 255, 255));
        labelAlamat.setText("Alamat :");

        labelTelepon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTelepon.setForeground(new java.awt.Color(255, 255, 255));
        labelTelepon.setText("Telepon :");

        inputTelepon.setBackground(new java.awt.Color(50, 50, 50));
        inputTelepon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTeleponActionPerformed(evt);
            }
        });
        inputTelepon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputTeleponFocusGained(evt);
            }
        });

        labelEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(255, 255, 255));
        labelEmail.setText("E-mail :");

        inputEmail.setBackground(new java.awt.Color(50, 50, 50));
        inputEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailActionPerformed(evt);
            }
        });
        inputEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputEmailFocusGained(evt);
            }
        });

        buttonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/reset.png"))); // NOI18N
        buttonReset.setText("Reset");
        buttonReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        inputTanggal_member.setEditable(false);
        inputTanggal_member.setBackground(new java.awt.Color(50, 50, 50));
        inputTanggal_member.setBorder(null);
        inputTanggal_member.setForeground(new java.awt.Color(50, 50, 50));
        inputTanggal_member.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd MMMM yyyy"))));

        labelFokusEmail.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelFokusEmail.setForeground(new java.awt.Color(255, 255, 255));

        labelFokusTelepon.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelFokusTelepon.setForeground(new java.awt.Color(255, 255, 255));

        labelFokusId_member.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelFokusId_member.setForeground(new java.awt.Color(255, 255, 255));

        buttonLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/laporan.png"))); // NOI18N
        buttonLaporan.setText("Cetak Laporan");
        buttonLaporan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLaporanActionPerformed(evt);
            }
        });

        buttonBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/kembali.png"))); // NOI18N
        buttonBack1.setText("Kembali");
        buttonBack1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMain1Layout = new javax.swing.GroupLayout(panelMain1);
        panelMain1.setLayout(panelMain1Layout);
        panelMain1Layout.setHorizontalGroup(
            panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMain1Layout.createSequentialGroup()
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMain1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelKodeMember, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNama, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelAlamat, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelTelepon, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMain1Layout.createSequentialGroup()
                                .addComponent(inputTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelFokusTelepon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelMain1Layout.createSequentialGroup()
                                .addComponent(inputId_member, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelFokusId_member, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelMain1Layout.createSequentialGroup()
                                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panelMain1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(labelEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelFokusEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputTanggal_member, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelMain1Layout.createSequentialGroup()
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMain1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane))
                    .addGroup(panelMain1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(186, 186, 186)
                        .addComponent(buttonBack1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonInsertMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUpdateMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDeleteMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        panelMain1Layout.setVerticalGroup(
            panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMain1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(inputId_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKodeMember)
                    .addComponent(labelFokusId_member, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(inputAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAlamat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(inputTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTelepon)
                    .addComponent(labelFokusTelepon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail)
                    .addComponent(labelFokusEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTanggal_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonBack1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(buttonReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(buttonInsertMember, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(buttonUpdateMember, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(buttonDeleteMember, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        toolbar.setBackground(new java.awt.Color(50, 50, 50));
        toolbar.setRollover(true);

        buttonBerandaView.setBackground(new java.awt.Color(0, 0, 0));
        buttonBerandaView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/admin1.png"))); // NOI18N
        buttonBerandaView.setText("Beranda Admin");
        buttonBerandaView.setFocusable(false);
        buttonBerandaView.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonBerandaView.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        buttonBerandaView.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonBerandaView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBerandaViewActionPerformed(evt);
            }
        });
        toolbar.add(buttonBerandaView);

        jLabel4.setText("..");
        toolbar.add(jLabel4);

        buttonPenerbitView.setBackground(new java.awt.Color(0, 0, 0));
        buttonPenerbitView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/penerbit1.png"))); // NOI18N
        buttonPenerbitView.setText("Data Penerbit");
        buttonPenerbitView.setFocusable(false);
        buttonPenerbitView.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonPenerbitView.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        buttonPenerbitView.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonPenerbitView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPenerbitViewActionPerformed(evt);
            }
        });
        toolbar.add(buttonPenerbitView);

        jLabel6.setText("..");
        toolbar.add(jLabel6);

        buttonBukuView.setBackground(new java.awt.Color(0, 0, 0));
        buttonBukuView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/buku.png"))); // NOI18N
        buttonBukuView.setText("Data Buku");
        buttonBukuView.setFocusable(false);
        buttonBukuView.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonBukuView.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        buttonBukuView.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonBukuView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBukuViewActionPerformed(evt);
            }
        });
        toolbar.add(buttonBukuView);

        jLabel5.setText("..");
        toolbar.add(jLabel5);

        buttonPinjamView.setBackground(new java.awt.Color(0, 0, 0));
        buttonPinjamView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/peminjaman1.png"))); // NOI18N
        buttonPinjamView.setText("Data Peminjaman");
        buttonPinjamView.setFocusable(false);
        buttonPinjamView.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonPinjamView.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        buttonPinjamView.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonPinjamView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPinjamViewActionPerformed(evt);
            }
        });
        toolbar.add(buttonPinjamView);

        jLabel7.setText("..");
        toolbar.add(jLabel7);

        buttonJualBeliView.setBackground(new java.awt.Color(0, 0, 0));
        buttonJualBeliView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/penjualan.png"))); // NOI18N
        buttonJualBeliView.setText("Data Penjualan");
        buttonJualBeliView.setFocusable(false);
        buttonJualBeliView.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonJualBeliView.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        buttonJualBeliView.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonJualBeliView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJualBeliViewActionPerformed(evt);
            }
        });
        toolbar.add(buttonJualBeliView);

        javax.swing.GroupLayout panelParentLayout = new javax.swing.GroupLayout(panelParent);
        panelParent.setLayout(panelParentLayout);
        panelParentLayout.setHorizontalGroup(
            panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParentLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panelMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelParentLayout.setVerticalGroup(
            panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParentLayout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(panelMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelParent, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputId_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputId_memberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputId_memberActionPerformed

    private void buttonInsertMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertMemberActionPerformed
        // TODO add your handling code here:
        controller.insertMember(this);
    }//GEN-LAST:event_buttonInsertMemberActionPerformed

    private void buttonUpdateMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateMemberActionPerformed
        // TODO add your handling code here:
        controller.updateMember(this);
    }//GEN-LAST:event_buttonUpdateMemberActionPerformed

    private void buttonDeleteMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteMemberActionPerformed
        // TODO add your handling code here:
        controller.deleteMember(this);
    }//GEN-LAST:event_buttonDeleteMemberActionPerformed

    private void inputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaActionPerformed

    private void inputAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAlamatActionPerformed

    private void inputTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTeleponActionPerformed

    private void inputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        // TODO add your handling code here:
        controller.resetMember(this);
    }//GEN-LAST:event_buttonResetActionPerformed

    private void buttonBerandaViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBerandaViewActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AdminView().setVisible(true);
    }//GEN-LAST:event_buttonBerandaViewActionPerformed

    private void buttonPenerbitViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPenerbitViewActionPerformed
        // TODO add your handling code here:
        this.dispose();
        PenerbitView penerbit = new PenerbitView();
        try {
            penerbit.loadDatabase();
            penerbit.setVisible(true);
        } catch (PenerbitException ex) {
            Logger.getLogger(MemberView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MemberView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonPenerbitViewActionPerformed

    private void buttonBukuViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBukuViewActionPerformed
        // TODO add your handling code here:
        this.dispose();
        BukuView buku = new BukuView();
        try {
            buku.loadDatabase();
            buku.setVisible(true);
        } catch (BukuException ex) {
            Logger.getLogger(MemberView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MemberView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonBukuViewActionPerformed

    private void buttonPinjamViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPinjamViewActionPerformed
        // TODO add your handling code here:
        this.dispose();
        PinjamView pinjam = new PinjamView();
        try {
            pinjam.loadDatabase();
            pinjam.setVisible(true);
        } catch (PinjamException ex) {
            Logger.getLogger(MemberView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MemberView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonPinjamViewActionPerformed

    private void buttonJualBeliViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJualBeliViewActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JualBeliView jualbeli = new JualBeliView();
        try {
            jualbeli.loadDatabase();
            jualbeli.setVisible(true);
        } catch (JualBeliException ex) {
            Logger.getLogger(MemberView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MemberView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonJualBeliViewActionPerformed

    private void inputId_memberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputId_memberFocusGained
        // TODO add your handling code here:
        labelFokusId_member.setText("ID Member tidak dapat di-update, jika terjadi kesalahan hapus dulu data yang dimaksud");
        labelFokusTelepon.setText("");
        labelFokusEmail.setText("");
    }//GEN-LAST:event_inputId_memberFocusGained

    private void inputTeleponFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputTeleponFocusGained
        // TODO add your handling code here:
        labelFokusId_member.setText("");
        labelFokusTelepon.setText("Nomor telepon maksimum 12 karakter, misal: 085717598655");
        labelFokusEmail.setText("");
    }//GEN-LAST:event_inputTeleponFocusGained

    private void inputEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputEmailFocusGained
        // TODO add your handling code here:
        labelFokusId_member.setText("");
        labelFokusTelepon.setText("");
        labelFokusEmail.setText("Tuliskan alamat email yang valid, misal: fadilaandre@gmail.com");
    }//GEN-LAST:event_inputEmailFocusGained

    private void inputNamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNamaFocusGained
        // TODO add your handling code here:
        labelFokusId_member.setText("");
        labelFokusTelepon.setText("");
        labelFokusEmail.setText("");
    }//GEN-LAST:event_inputNamaFocusGained

    private void inputAlamatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputAlamatFocusGained
        // TODO add your handling code here:
        labelFokusId_member.setText("");
        labelFokusTelepon.setText("");
        labelFokusEmail.setText("");
    }//GEN-LAST:event_inputAlamatFocusGained

    private void buttonLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLaporanActionPerformed
        // TODO add your handling code here:
        try {
            File file = new File("src/faraz/view/laporan/DaftarMember.jrxml");
            jasperDesign = JRXmlLoader.load(file);
//            int row = tabelMember.getSelectedRow()-1;
//            String IDMember = (String) tabelMember.getValueAt(row, 1);
//            param.put(IDMember, IDMember);
            param.clear();
            jasperReport = JasperCompileManager.compileReport(jasperDesign);
            jasperPrint = JasperFillManager.fillReport(jasperReport, param, koneksi.getConnection());
            JasperViewer.viewReport(jasperPrint, false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_buttonLaporanActionPerformed

    private void buttonBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBack1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AdminView().setVisible(true);
    }//GEN-LAST:event_buttonBack1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private faraz.view.usu.Button buttonBack1;
    private faraz.view.usu.Button buttonBerandaView;
    private faraz.view.usu.Button buttonBukuView;
    private faraz.view.usu.Button buttonDeleteMember;
    private faraz.view.usu.Button buttonInsertMember;
    private faraz.view.usu.Button buttonJualBeliView;
    private faraz.view.usu.Button buttonLaporan;
    private faraz.view.usu.Button buttonPenerbitView;
    private faraz.view.usu.Button buttonPinjamView;
    private faraz.view.usu.Button buttonReset;
    private faraz.view.usu.Button buttonUpdateMember;
    private faraz.view.usu.TextBox inputAlamat;
    private faraz.view.usu.TextBox inputEmail;
    private faraz.view.usu.TextBox inputId_member;
    private faraz.view.usu.TextBox inputNama;
    private javax.swing.JFormattedTextField inputTanggal_member;
    private faraz.view.usu.TextBox inputTelepon;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFokusEmail;
    private javax.swing.JLabel labelFokusId_member;
    private javax.swing.JLabel labelFokusTelepon;
    private javax.swing.JLabel labelKodeMember;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelTelepon;
    private javax.swing.JPanel panelMain1;
    private faraz.view.usu.Panel panelParent;
    private javax.swing.JTable tabelMember;
    private faraz.view.usu.Toolbar toolbar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(MemberModel model) {
        inputId_member.setText(model.getId_member());
        inputNama.setText(model.getNama());
        inputAlamat.setText(model.getAlamat());
        inputTelepon.setText(model.getTelepon());
        inputEmail.setText(model.getEmail());
        inputTanggal_member.setValue(model.getTanggal_member());
    }

    @Override
    public void onInsert(Member member) {
        tableModel.add(member);
    }

    @Override
    public void onUpdate(Member member) {
        int index = tabelMember.getSelectedRow();
        tableModel.set(index, member);
    }

    @Override
    public void onDelete() {
        int index = tabelMember.getSelectedRow();
        tableModel.remove(index);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        try {
            Member model = tableModel.get(tabelMember.getSelectedRow());
            inputId_member.setText(model.getId_member());
            inputNama.setText(model.getNama());
            inputAlamat.setText(model.getAlamat());
            inputTelepon.setText(model.getTelepon());
            inputEmail.setText(model.getEmail());
            inputTanggal_member.setValue(model.getTanggal_member());
        } catch (IndexOutOfBoundsException exception) {
        }
    }

    public void loadDatabase() throws MemberException, SQLException {
        MemberDao dao = MemberDatabase.getMemberDao();
        tableModel.setList(dao.selectAllMember());
    }
}
