/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package faraz.view;

import faraz.controller.MengelolaMember;
import faraz.database.MemberDatabase;
import faraz.entity.Member;
import faraz.error.*;
import faraz.model.MemberModel;
import faraz.model.TableMemberModel;
import faraz.model.event.MemberListener;
import faraz.service.MemberDao;
import faraz.view.usu.TextBox;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author FAM
 */
public class MemberKasirView extends javax.swing.JFrame implements MemberListener, ListSelectionListener {

    private TableMemberModel tableModel;
    private MemberModel model;
    private MengelolaMember controller;

    /**
     * Creates new form MemberView2
     */
    public MemberKasirView() {
        tableModel = new TableMemberModel();

        model = new MemberModel();
        model.setListener(this);

        controller = new MengelolaMember();
        controller.setModel(model);

        initComponents();
        setTitle("Data Member - Admin Faraz Information System (FISt)");
        setExtendedState(MAXIMIZED_BOTH);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ImageIcon img = new ImageIcon("src/faraz/view/images/library.png");
        setIconImage(img.getImage());

        tabelMember.getSelectionModel().addListSelectionListener(this);
        tabelMember.setModel(tableModel);
        tabelMember.getTableHeader().setReorderingAllowed(false);
        tabelMember.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 14));
        tabelMember.getTableHeader().setBackground(Color.CYAN);
    }

    public JTable getTabelMember() {
        return tabelMember;
    }

    public TextBox getInputAlamat() {
        return inputAlamat;
    }

    public TextBox getInputEmail() {
        return inputEmail;
    }

    public TextBox getInputId_member() {
        return inputId_member;
    }

    public TextBox getInputNama() {
        return inputNama;
    }

    public TextBox getInputTelepon() {
        return inputTelepon;
    }

    public JFormattedTextField getInputTanggal_member() {
        return inputTanggal_member;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelParent = new faraz.view.usu.Panel();
        panelMain1 = new javax.swing.JPanel();
        labelKodeMember = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tabelMember = new javax.swing.JTable();
        inputId_member = new faraz.view.usu.TextBox();
        buttonInsertMember = new faraz.view.usu.Button();
        buttonUpdateMember = new faraz.view.usu.Button();
        buttonDeleteMember = new faraz.view.usu.Button();
        labelNama = new javax.swing.JLabel();
        inputNama = new faraz.view.usu.TextBox();
        inputAlamat = new faraz.view.usu.TextBox();
        labelAlamat = new javax.swing.JLabel();
        labelTelepon = new javax.swing.JLabel();
        inputTelepon = new faraz.view.usu.TextBox();
        labelEmail = new javax.swing.JLabel();
        inputEmail = new faraz.view.usu.TextBox();
        buttonReset = new faraz.view.usu.Button();
        inputTanggal_member = new javax.swing.JFormattedTextField();
        labelFokusId_member = new javax.swing.JLabel();
        labelFokusTelepon = new javax.swing.JLabel();
        labelFokusEmail = new javax.swing.JLabel();
        buttonBack1 = new faraz.view.usu.Button();
        toolbar = new faraz.view.usu.Toolbar();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelParent.setMaximumSize(new java.awt.Dimension(800, 600));
        panelParent.setPreferredSize(new java.awt.Dimension(800, 600));

        panelMain1.setBackground(new java.awt.Color(50, 50, 50));

        labelKodeMember.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelKodeMember.setForeground(new java.awt.Color(255, 255, 255));
        labelKodeMember.setText("ID Member :");

        tabelMember.setBackground(new java.awt.Color(50, 50, 50));
        tabelMember.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tabelMember.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tabelMember.setForeground(new java.awt.Color(255, 255, 255));
        tabelMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane.setViewportView(tabelMember);

        inputId_member.setBackground(new java.awt.Color(50, 50, 50));
        inputId_member.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputId_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputId_memberActionPerformed(evt);
            }
        });
        inputId_member.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputId_memberFocusGained(evt);
            }
        });

        buttonInsertMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/tambah.png"))); // NOI18N
        buttonInsertMember.setText("Tambah");
        buttonInsertMember.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonInsertMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertMemberActionPerformed(evt);
            }
        });

        buttonUpdateMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/update.png"))); // NOI18N
        buttonUpdateMember.setText("Update");
        buttonUpdateMember.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonUpdateMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateMemberActionPerformed(evt);
            }
        });

        buttonDeleteMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/hapus.png"))); // NOI18N
        buttonDeleteMember.setText("Hapus");
        buttonDeleteMember.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonDeleteMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteMemberActionPerformed(evt);
            }
        });

        labelNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNama.setForeground(new java.awt.Color(255, 255, 255));
        labelNama.setText("Nama :");

        inputNama.setBackground(new java.awt.Color(50, 50, 50));
        inputNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaActionPerformed(evt);
            }
        });
        inputNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNamaFocusGained(evt);
            }
        });

        inputAlamat.setBackground(new java.awt.Color(50, 50, 50));
        inputAlamat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAlamatActionPerformed(evt);
            }
        });
        inputAlamat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputAlamatFocusGained(evt);
            }
        });

        labelAlamat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelAlamat.setForeground(new java.awt.Color(255, 255, 255));
        labelAlamat.setText("Alamat :");

        labelTelepon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTelepon.setForeground(new java.awt.Color(255, 255, 255));
        labelTelepon.setText("Telepon :");

        inputTelepon.setBackground(new java.awt.Color(50, 50, 50));
        inputTelepon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTeleponActionPerformed(evt);
            }
        });
        inputTelepon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputTeleponFocusGained(evt);
            }
        });

        labelEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(255, 255, 255));
        labelEmail.setText("E-mail :");

        inputEmail.setBackground(new java.awt.Color(50, 50, 50));
        inputEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailActionPerformed(evt);
            }
        });
        inputEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputEmailFocusGained(evt);
            }
        });

        buttonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/reset.png"))); // NOI18N
        buttonReset.setText("Reset");
        buttonReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        inputTanggal_member.setEditable(false);
        inputTanggal_member.setBackground(new java.awt.Color(50, 50, 50));
        inputTanggal_member.setBorder(null);
        inputTanggal_member.setForeground(new java.awt.Color(50, 50, 50));
        inputTanggal_member.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd MMMM yyyy"))));

        labelFokusId_member.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelFokusId_member.setForeground(new java.awt.Color(255, 255, 255));

        labelFokusTelepon.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelFokusTelepon.setForeground(new java.awt.Color(255, 255, 255));

        labelFokusEmail.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelFokusEmail.setForeground(new java.awt.Color(255, 255, 255));

        buttonBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/kembali.png"))); // NOI18N
        buttonBack1.setText("Kembali");
        buttonBack1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMain1Layout = new javax.swing.GroupLayout(panelMain1);
        panelMain1.setLayout(panelMain1Layout);
        panelMain1Layout.setHorizontalGroup(
            panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMain1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAlamat, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNama, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelKodeMember, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTelepon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelEmail, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMain1Layout.createSequentialGroup()
                        .addComponent(inputId_member, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelFokusId_member, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelMain1Layout.createSequentialGroup()
                        .addComponent(inputTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelFokusTelepon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelMain1Layout.createSequentialGroup()
                        .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelMain1Layout.createSequentialGroup()
                                .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelFokusEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputTanggal_member, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelMain1Layout.createSequentialGroup()
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMain1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane))
                    .addGroup(panelMain1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonBack1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(312, 312, 312)
                        .addComponent(buttonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonInsertMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUpdateMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDeleteMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        panelMain1Layout.setVerticalGroup(
            panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMain1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(inputId_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKodeMember)
                    .addComponent(labelFokusId_member, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(inputAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAlamat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(inputTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTelepon)
                    .addComponent(labelFokusTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail)
                    .addComponent(labelFokusEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTanggal_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(buttonDeleteMember, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonUpdateMember, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonInsertMember, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBack1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        toolbar.setBackground(new java.awt.Color(50, 50, 50));
        toolbar.setRollover(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Data Member");
        toolbar.add(jLabel2);

        javax.swing.GroupLayout panelParentLayout = new javax.swing.GroupLayout(panelParent);
        panelParent.setLayout(panelParentLayout);
        panelParentLayout.setHorizontalGroup(
            panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParentLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panelMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelParentLayout.setVerticalGroup(
            panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParentLayout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(panelMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelParent, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputId_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputId_memberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputId_memberActionPerformed

    private void buttonInsertMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertMemberActionPerformed
        // TODO add your handling code here:
        controller.insertMember(this);
    }//GEN-LAST:event_buttonInsertMemberActionPerformed

    private void buttonUpdateMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateMemberActionPerformed
        // TODO add your handling code here:
        controller.updateMember(this);
    }//GEN-LAST:event_buttonUpdateMemberActionPerformed

    private void buttonDeleteMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteMemberActionPerformed
        // TODO add your handling code here:
        controller.deleteMember(this);
    }//GEN-LAST:event_buttonDeleteMemberActionPerformed

    private void inputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaActionPerformed

    private void inputAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAlamatActionPerformed

    private void inputTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTeleponActionPerformed

    private void inputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        // TODO add your handling code here:
        controller.resetMember(this);
    }//GEN-LAST:event_buttonResetActionPerformed

    private void inputId_memberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputId_memberFocusGained
        // TODO add your handling code here:
        labelFokusId_member.setText("ID Member tidak dapat di-update, jika terjadi kesalahan hapus dulu data yang dimaksud");
        labelFokusTelepon.setText("");
        labelFokusEmail.setText("");
    }//GEN-LAST:event_inputId_memberFocusGained

    private void inputTeleponFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputTeleponFocusGained
        // TODO add your handling code here:
        labelFokusId_member.setText("");
        labelFokusTelepon.setText("Nomor telepon maksimum 12 karakter, misal: 085717598655");
        labelFokusEmail.setText("");
    }//GEN-LAST:event_inputTeleponFocusGained

    private void inputEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputEmailFocusGained
        // TODO add your handling code here:
        labelFokusId_member.setText("");
        labelFokusTelepon.setText("");
        labelFokusEmail.setText("Tuliskan alamat email yang valid, misal: fadilaandre@gmail.com");
    }//GEN-LAST:event_inputEmailFocusGained

    private void inputNamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNamaFocusGained
        // TODO add your handling code here:
        labelFokusId_member.setText("");
        labelFokusTelepon.setText("");
        labelFokusEmail.setText("");
    }//GEN-LAST:event_inputNamaFocusGained

    private void inputAlamatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputAlamatFocusGained
        // TODO add your handling code here:
        labelFokusId_member.setText("");
        labelFokusTelepon.setText("");
        labelFokusEmail.setText("");
    }//GEN-LAST:event_inputAlamatFocusGained

    private void buttonBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBack1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonBack1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private faraz.view.usu.Button buttonBack1;
    private faraz.view.usu.Button buttonDeleteMember;
    private faraz.view.usu.Button buttonInsertMember;
    private faraz.view.usu.Button buttonReset;
    private faraz.view.usu.Button buttonUpdateMember;
    private faraz.view.usu.TextBox inputAlamat;
    private faraz.view.usu.TextBox inputEmail;
    private faraz.view.usu.TextBox inputId_member;
    private faraz.view.usu.TextBox inputNama;
    private javax.swing.JFormattedTextField inputTanggal_member;
    private faraz.view.usu.TextBox inputTelepon;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFokusEmail;
    private javax.swing.JLabel labelFokusId_member;
    private javax.swing.JLabel labelFokusTelepon;
    private javax.swing.JLabel labelKodeMember;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelTelepon;
    private javax.swing.JPanel panelMain1;
    private faraz.view.usu.Panel panelParent;
    private javax.swing.JTable tabelMember;
    private faraz.view.usu.Toolbar toolbar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(MemberModel model) {
        inputId_member.setText(model.getId_member());
        inputNama.setText(model.getNama());
        inputAlamat.setText(model.getAlamat());
        inputTelepon.setText(model.getTelepon());
        inputEmail.setText(model.getEmail());
        inputTanggal_member.setValue(model.getTanggal_member());
    }

    @Override
    public void onInsert(Member member) {
        tableModel.add(member);
    }

    @Override
    public void onUpdate(Member member) {
        int index = tabelMember.getSelectedRow();
        tableModel.set(index, member);
    }

    @Override
    public void onDelete() {
        int index = tabelMember.getSelectedRow();
        tableModel.remove(index);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        try {
            Member model = tableModel.get(tabelMember.getSelectedRow());
            inputId_member.setText(model.getId_member());
            inputNama.setText(model.getNama());
            inputAlamat.setText(model.getAlamat());
            inputTelepon.setText(model.getTelepon());
            inputEmail.setText(model.getEmail());
            inputTanggal_member.setValue(model.getTanggal_member());
        } catch (IndexOutOfBoundsException exception) {
        }
    }

    public void loadDatabase() throws MemberException, SQLException {
        MemberDao dao = MemberDatabase.getMemberDao();
        tableModel.setList(dao.selectAllMember());
    }
}
