/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package faraz.view;

import faraz.controller.GantiPassword;
import faraz.database.AdminDatabase;
import faraz.entity.Admin;
import faraz.error.AdminException;
import faraz.service.AdminDao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author FAM
 */
public class PasswordAdminView extends javax.swing.JDialog {
    
    
    private GantiPassword controller;
    /**
     * Creates new form LoginAdminView
     */
    public PasswordAdminView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Ganti Password Admin - Admin Faraz Information System (FISt)");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelParent = new faraz.view.usu.Panel();
        toolbar = new faraz.view.usu.Toolbar();
        labelLoginAdmin = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        inputUsername = new faraz.view.usu.TextBox();
        labelUsername = new javax.swing.JLabel();
        inputPassword_lama = new faraz.view.usu.PasswordBox();
        btnChange = new faraz.view.usu.Button();
        btnCancel = new faraz.view.usu.Button();
        labelValidasi = new javax.swing.JLabel();
        inputPassword_baru = new faraz.view.usu.PasswordBox();
        labelPassword_baru = new javax.swing.JLabel();
        labelKonfirmasi = new javax.swing.JLabel();
        inputPassword_konfirmasi = new faraz.view.usu.PasswordBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelParent.setMaximumSize(new java.awt.Dimension(400, 300));
        panelParent.setPreferredSize(new java.awt.Dimension(400, 300));

        toolbar.setBackground(new java.awt.Color(50, 50, 50));
        toolbar.setRollover(true);

        labelLoginAdmin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelLoginAdmin.setForeground(new java.awt.Color(255, 255, 255));
        labelLoginAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelLoginAdmin.setText("Ganti Password");
        toolbar.add(labelLoginAdmin);

        labelPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(255, 255, 255));
        labelPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPassword.setText("Password Lama :");

        inputUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        labelUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(255, 255, 255));
        labelUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUsername.setText("Username :");

        inputPassword_lama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputPassword_lama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPassword_lamaActionPerformed(evt);
            }
        });

        btnChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/login.png"))); // NOI18N
        btnChange.setText("Ganti");
        btnChange.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/batal.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        labelValidasi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelValidasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        inputPassword_baru.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputPassword_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPassword_baruActionPerformed(evt);
            }
        });

        labelPassword_baru.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPassword_baru.setForeground(new java.awt.Color(255, 255, 255));
        labelPassword_baru.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPassword_baru.setText("Password Baru :");

        labelKonfirmasi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelKonfirmasi.setForeground(new java.awt.Color(255, 255, 255));
        labelKonfirmasi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelKonfirmasi.setText("Konfirmasi Password :");

        inputPassword_konfirmasi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputPassword_konfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPassword_konfirmasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelParentLayout = new javax.swing.GroupLayout(panelParent);
        panelParent.setLayout(panelParentLayout);
        panelParentLayout.setHorizontalGroup(
            panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(panelParentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelValidasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelParentLayout.createSequentialGroup()
                        .addGroup(panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelParentLayout.createSequentialGroup()
                                .addGroup(panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelPassword_baru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelKonfirmasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputPassword_lama, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputPassword_baru, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputPassword_konfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelParentLayout.createSequentialGroup()
                                .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelParentLayout.setVerticalGroup(
            panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParentLayout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword)
                    .addComponent(inputPassword_lama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword_baru)
                    .addComponent(inputPassword_baru, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKonfirmasi)
                    .addComponent(inputPassword_konfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(labelValidasi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelParent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelParent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputPassword_lamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPassword_lamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPassword_lamaActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
        
        controller = new GantiPassword();
        String username = this.inputUsername.getText();
        String pass_lama = this.inputPassword_lama.getText();
        String pass_baru = this.inputPassword_baru.getText();
        String pass_konfirmasi = this.inputPassword_konfirmasi.getText();
        
        controller.updateAkun(this, username, pass_lama, pass_baru, pass_konfirmasi);
        
       
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void inputPassword_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPassword_baruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPassword_baruActionPerformed

    private void inputPassword_konfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPassword_konfirmasiActionPerformed
        // TODO add your handling code here:
        btnChangeActionPerformed(evt);
    }//GEN-LAST:event_inputPassword_konfirmasiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private faraz.view.usu.Button btnCancel;
    private faraz.view.usu.Button btnChange;
    public faraz.view.usu.PasswordBox inputPassword_baru;
    public faraz.view.usu.PasswordBox inputPassword_konfirmasi;
    public faraz.view.usu.PasswordBox inputPassword_lama;
    public faraz.view.usu.TextBox inputUsername;
    private javax.swing.JLabel labelKonfirmasi;
    private javax.swing.JLabel labelLoginAdmin;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelPassword_baru;
    private javax.swing.JLabel labelUsername;
    public javax.swing.JLabel labelValidasi;
    private faraz.view.usu.Panel panelParent;
    private faraz.view.usu.Toolbar toolbar;
    // End of variables declaration//GEN-END:variables
}
