/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package faraz.view;

import faraz.controller.MengelolaPenerbit;
import faraz.database.PenerbitDatabase;
import faraz.entity.Penerbit;
import faraz.error.*;
import faraz.model.PenerbitModel;
import faraz.model.TablePenerbitModel;
import faraz.model.event.PenerbitListener;
import faraz.service.PenerbitDao;
import faraz.view.usu.TextBox;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author FAM
 */
public class PenerbitKasirView extends javax.swing.JFrame implements PenerbitListener, ListSelectionListener {

    private TablePenerbitModel tableModel;
    private PenerbitModel model;
    private MengelolaPenerbit controller;

    /**
     * Creates new form PenerbitView2
     */
    public PenerbitKasirView() {
        tableModel = new TablePenerbitModel();

        model = new PenerbitModel();
        model.setListener(this);

        controller = new MengelolaPenerbit();
        controller.setModel(model);

        initComponents();
        setTitle("Data Penerbit - Admin Faraz Information System (FISt)");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        ImageIcon img = new ImageIcon("src/faraz/view/images/library.png");
        setIconImage(img.getImage());

        tabelPenerbit.getSelectionModel().addListSelectionListener(this);
        tabelPenerbit.setModel(tableModel);
        tabelPenerbit.getTableHeader().setReorderingAllowed(false);
        tabelPenerbit.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 14));
        tabelPenerbit.getTableHeader().setBackground(Color.CYAN);
    }

    public JTable getTabelPenerbit() {
        return tabelPenerbit;
    }

    public TextBox getInputId_penerbit() {
        return inputId_penerbit;
    }

    public TextBox getInputNama_penerbit() {
        return inputNama_penerbit;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelParent = new faraz.view.usu.Panel();
        panelMain1 = new javax.swing.JPanel();
        labelIdPenerbit = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tabelPenerbit = new javax.swing.JTable();
        inputId_penerbit = new faraz.view.usu.TextBox();
        buttonInsertPenerbit = new faraz.view.usu.Button();
        buttonUpdatePenerbit = new faraz.view.usu.Button();
        buttonDeletePenerbit = new faraz.view.usu.Button();
        labelNamaPenerbit = new javax.swing.JLabel();
        inputNama_penerbit = new faraz.view.usu.TextBox();
        buttonReset = new faraz.view.usu.Button();
        labelFokusId_penerbit = new javax.swing.JLabel();
        labelFokusNama_penerbit = new javax.swing.JLabel();
        buttonBack1 = new faraz.view.usu.Button();
        toolbar = new faraz.view.usu.Toolbar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelParent.setMaximumSize(new java.awt.Dimension(800, 600));
        panelParent.setPreferredSize(new java.awt.Dimension(800, 600));

        panelMain1.setBackground(new java.awt.Color(50, 50, 50));

        labelIdPenerbit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelIdPenerbit.setForeground(new java.awt.Color(255, 255, 255));
        labelIdPenerbit.setText("ID Penerbit :");

        tabelPenerbit.setBackground(new java.awt.Color(50, 50, 50));
        tabelPenerbit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tabelPenerbit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tabelPenerbit.setForeground(new java.awt.Color(255, 255, 255));
        tabelPenerbit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane.setViewportView(tabelPenerbit);

        inputId_penerbit.setBackground(new java.awt.Color(50, 50, 50));
        inputId_penerbit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputId_penerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputId_penerbitActionPerformed(evt);
            }
        });
        inputId_penerbit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputId_penerbitFocusGained(evt);
            }
        });

        buttonInsertPenerbit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/tambah.png"))); // NOI18N
        buttonInsertPenerbit.setText("Tambah");
        buttonInsertPenerbit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonInsertPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertPenerbitActionPerformed(evt);
            }
        });

        buttonUpdatePenerbit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/update.png"))); // NOI18N
        buttonUpdatePenerbit.setText("Update");
        buttonUpdatePenerbit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonUpdatePenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdatePenerbitActionPerformed(evt);
            }
        });

        buttonDeletePenerbit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/hapus.png"))); // NOI18N
        buttonDeletePenerbit.setText("Hapus");
        buttonDeletePenerbit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonDeletePenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeletePenerbitActionPerformed(evt);
            }
        });

        labelNamaPenerbit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNamaPenerbit.setForeground(new java.awt.Color(255, 255, 255));
        labelNamaPenerbit.setText("Nama Penerbit :");

        inputNama_penerbit.setBackground(new java.awt.Color(50, 50, 50));
        inputNama_penerbit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputNama_penerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNama_penerbitActionPerformed(evt);
            }
        });
        inputNama_penerbit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNama_penerbitFocusGained(evt);
            }
        });

        buttonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/reset.png"))); // NOI18N
        buttonReset.setText("Reset");
        buttonReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        labelFokusId_penerbit.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelFokusId_penerbit.setForeground(new java.awt.Color(255, 255, 255));

        labelFokusNama_penerbit.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelFokusNama_penerbit.setForeground(new java.awt.Color(255, 255, 255));

        buttonBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/kembali.png"))); // NOI18N
        buttonBack1.setText("Kembali");
        buttonBack1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMain1Layout = new javax.swing.GroupLayout(panelMain1);
        panelMain1.setLayout(panelMain1Layout);
        panelMain1Layout.setHorizontalGroup(
            panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMain1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMain1Layout.createSequentialGroup()
                        .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNamaPenerbit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelIdPenerbit, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMain1Layout.createSequentialGroup()
                                .addComponent(inputId_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelFokusId_penerbit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelMain1Layout.createSequentialGroup()
                                .addComponent(inputNama_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelFokusNama_penerbit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(panelMain1Layout.createSequentialGroup()
                        .addComponent(buttonBack1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(310, 310, 310)
                        .addComponent(buttonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonInsertPenerbit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUpdatePenerbit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDeletePenerbit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(panelMain1Layout.createSequentialGroup()
                        .addComponent(jScrollPane)
                        .addContainerGap())))
        );
        panelMain1Layout.setVerticalGroup(
            panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMain1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(inputId_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIdPenerbit)
                    .addComponent(labelFokusId_penerbit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFokusNama_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputNama_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelNamaPenerbit)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(buttonDeletePenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonUpdatePenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonInsertPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBack1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        toolbar.setBackground(new java.awt.Color(50, 50, 50));
        toolbar.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Data Penerbit");
        toolbar.add(jLabel1);

        javax.swing.GroupLayout panelParentLayout = new javax.swing.GroupLayout(panelParent);
        panelParent.setLayout(panelParentLayout);
        panelParentLayout.setHorizontalGroup(
            panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParentLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panelMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelParentLayout.setVerticalGroup(
            panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParentLayout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(panelMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelParent, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputId_penerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputId_penerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputId_penerbitActionPerformed

    private void buttonInsertPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertPenerbitActionPerformed
        // TODO add your handling code here:
        controller.insertPenerbit(this);
    }//GEN-LAST:event_buttonInsertPenerbitActionPerformed

    private void buttonUpdatePenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdatePenerbitActionPerformed
        // TODO add your handling code here:
        controller.updatePenerbit(this);
    }//GEN-LAST:event_buttonUpdatePenerbitActionPerformed

    private void buttonDeletePenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeletePenerbitActionPerformed
        // TODO add your handling code here:
        controller.deletePenerbit(this);
    }//GEN-LAST:event_buttonDeletePenerbitActionPerformed

    private void inputNama_penerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNama_penerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNama_penerbitActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        // TODO add your handling code here:
        controller.resetPenerbit(this);
    }//GEN-LAST:event_buttonResetActionPerformed

    private void inputId_penerbitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputId_penerbitFocusGained
        // TODO add your handling code here:
        labelFokusId_penerbit.setText("ID Penerbit maksimum 3 karakter (boleh angka/huruf)");
        labelFokusNama_penerbit.setText("");
    }//GEN-LAST:event_inputId_penerbitFocusGained

    private void inputNama_penerbitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNama_penerbitFocusGained
        // TODO add your handling code here:
        labelFokusNama_penerbit.setText("Tuliskan nama lengkap penerbit");
        labelFokusId_penerbit.setText("");
    }//GEN-LAST:event_inputNama_penerbitFocusGained

    private void buttonBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBack1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonBack1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private faraz.view.usu.Button buttonBack1;
    private faraz.view.usu.Button buttonDeletePenerbit;
    private faraz.view.usu.Button buttonInsertPenerbit;
    private faraz.view.usu.Button buttonReset;
    private faraz.view.usu.Button buttonUpdatePenerbit;
    private faraz.view.usu.TextBox inputId_penerbit;
    private faraz.view.usu.TextBox inputNama_penerbit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel labelFokusId_penerbit;
    private javax.swing.JLabel labelFokusNama_penerbit;
    private javax.swing.JLabel labelIdPenerbit;
    private javax.swing.JLabel labelNamaPenerbit;
    private javax.swing.JPanel panelMain1;
    private faraz.view.usu.Panel panelParent;
    private javax.swing.JTable tabelPenerbit;
    private faraz.view.usu.Toolbar toolbar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(PenerbitModel model) {
        inputId_penerbit.setText(model.getId_penerbit());
        inputNama_penerbit.setText(model.getNama_penerbit());
    }

    @Override
    public void onInsert(Penerbit penerbit) {
        tableModel.add(penerbit);
    }

    @Override
    public void onUpdate(Penerbit penerbit) {
        int index = tabelPenerbit.getSelectedRow();
        tableModel.set(index, penerbit);
    }

    @Override
    public void onDelete() {
        int index = tabelPenerbit.getSelectedRow();
        tableModel.remove(index);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        try {
            Penerbit model = tableModel.get(tabelPenerbit.getSelectedRow());
            inputId_penerbit.setText(model.getId_penerbit());
            inputNama_penerbit.setText(model.getNama_penerbit());
        } catch (IndexOutOfBoundsException exception) {
        }
    }

    public void loadDatabase() throws PenerbitException, SQLException {
        PenerbitDao dao = PenerbitDatabase.getPenerbitDao();
        tableModel.setList(dao.selectAllPenerbit());
    }
}
