/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package faraz.view;

import faraz.controller.MengelolaBuku;
import faraz.controller.MengelolaPeminjaman;
//import faraz.controller.MengelolaPengembalian;
import faraz.database.PinjamDatabase;
import faraz.entity.Pinjam;
import faraz.error.PinjamException;
import faraz.model.BukuModel;
import faraz.model.PinjamModel;
import faraz.model.TablePengembalianKasirModel;
import faraz.model.event.PinjamListener;
import faraz.service.PinjamDao;
import faraz.view.usu.TextBox;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author FAM
 */
public class PengembalianKasirView extends javax.swing.JFrame implements PinjamListener, ListSelectionListener {

    private PinjamModel pinjamModel;
    private MengelolaPeminjaman pinjamController;
    //private MengelolaPengembalian kembaliController;
    private BukuModel bukuModel;
    private MengelolaBuku bukuController;
    private TablePengembalianKasirModel tableModel;

    /**
     * Creates new form PengembalianKasirView
     */
    public PengembalianKasirView() {
        tableModel = new TablePengembalianKasirModel();

        pinjamModel = new PinjamModel();
        pinjamController = new MengelolaPeminjaman();
        pinjamController.setModel(pinjamModel);

        bukuModel = new BukuModel();
        bukuController = new MengelolaBuku();
        bukuController.setModel(bukuModel);

        initComponents();
        setTitle("Pengembalian Buku - Faraz Information System (FISt)");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        ImageIcon img = new ImageIcon("src/faraz/view/images/library.png");
        setIconImage(img.getImage());

        tabelPinjam.getSelectionModel().addListSelectionListener(this);
        tabelPinjam.setModel(tableModel);
        tabelPinjam.getTableHeader().setReorderingAllowed(false);
        tabelPinjam.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 16));
        tabelPinjam.getTableHeader().setBackground(Color.CYAN);
    }

    public TextBox getInputDenda() {
        return inputDenda;
    }

    public TextBox getInputId_member() {
        return inputId_member;
    }

    public JTable getTabelPinjam() {
        return tabelPinjam;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelParent = new faraz.view.usu.Panel();
        toolbar = new faraz.view.usu.Toolbar();
        jLabel1 = new javax.swing.JLabel();
        panelMain1 = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        tabelPinjam = new javax.swing.JTable();
        inputId_member = new faraz.view.usu.TextBox();
        labelId_member = new javax.swing.JLabel();
        labeDenda = new javax.swing.JLabel();
        inputDenda = new faraz.view.usu.TextBox();
        buttonCheck = new faraz.view.usu.Button();
        buttonBatal = new faraz.view.usu.Button();
        buttonUpdatePinjam = new faraz.view.usu.Button();
        buttonReset = new faraz.view.usu.Button();
        labelFokusId_member = new javax.swing.JLabel();
        labelFokusDenda = new javax.swing.JLabel();
        buttonBack1 = new faraz.view.usu.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelParent.setMaximumSize(new java.awt.Dimension(800, 600));
        panelParent.setPreferredSize(new java.awt.Dimension(800, 600));

        toolbar.setBackground(new java.awt.Color(50, 50, 50));
        toolbar.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Pengembalian Buku");
        toolbar.add(jLabel1);

        panelMain1.setBackground(new java.awt.Color(50, 50, 50));
        panelMain1.setMaximumSize(new java.awt.Dimension(1280, 800));

        tabelPinjam.setBackground(new java.awt.Color(50, 50, 50));
        tabelPinjam.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tabelPinjam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabelPinjam.setForeground(new java.awt.Color(255, 255, 255));
        tabelPinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane.setViewportView(tabelPinjam);

        inputId_member.setBackground(new java.awt.Color(50, 50, 50));
        inputId_member.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputId_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputId_memberActionPerformed(evt);
            }
        });
        inputId_member.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputId_memberFocusGained(evt);
            }
        });
        inputId_member.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputId_memberKeyPressed(evt);
            }
        });

        labelId_member.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelId_member.setForeground(new java.awt.Color(255, 255, 255));
        labelId_member.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelId_member.setText("ID Member :");

        labeDenda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labeDenda.setForeground(new java.awt.Color(255, 255, 255));
        labeDenda.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labeDenda.setText("Denda :");

        inputDenda.setBackground(new java.awt.Color(50, 50, 50));
        inputDenda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputDenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDendaActionPerformed(evt);
            }
        });
        inputDenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputDendaFocusGained(evt);
            }
        });

        buttonCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/check.png"))); // NOI18N
        buttonCheck.setText("Check");
        buttonCheck.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCheckActionPerformed(evt);
            }
        });

        buttonBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/batal.png"))); // NOI18N
        buttonBatal.setText("Batal");
        buttonBatal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        buttonUpdatePinjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/simpan.png"))); // NOI18N
        buttonUpdatePinjam.setText("Simpan");
        buttonUpdatePinjam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonUpdatePinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdatePinjamActionPerformed(evt);
            }
        });

        buttonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/reset.png"))); // NOI18N
        buttonReset.setText("Reset");
        buttonReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        labelFokusId_member.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelFokusId_member.setForeground(new java.awt.Color(255, 255, 255));
        labelFokusId_member.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        labelFokusDenda.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelFokusDenda.setForeground(new java.awt.Color(255, 255, 255));
        labelFokusDenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        buttonBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faraz/view/images/kembali.png"))); // NOI18N
        buttonBack1.setText("Kembali");
        buttonBack1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMain1Layout = new javax.swing.GroupLayout(panelMain1);
        panelMain1.setLayout(panelMain1Layout);
        panelMain1Layout.setHorizontalGroup(
            panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMain1Layout.createSequentialGroup()
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMain1Layout.createSequentialGroup()
                        .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMain1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelFokusDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(panelMain1Layout.createSequentialGroup()
                                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelMain1Layout.createSequentialGroup()
                                            .addGap(16, 16, 16)
                                            .addComponent(labelId_member, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(inputId_member, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelMain1Layout.createSequentialGroup()
                                            .addGap(41, 41, 41)
                                            .addComponent(labeDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(inputDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMain1Layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(buttonCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panelMain1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(buttonBack1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)))
                        .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane)
                            .addGroup(panelMain1Layout.createSequentialGroup()
                                .addComponent(buttonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(232, 232, 232)
                                .addComponent(buttonBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonUpdatePinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panelMain1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelFokusId_member, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelMain1Layout.setVerticalGroup(
            panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMain1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMain1Layout.createSequentialGroup()
                        .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonUpdatePinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelMain1Layout.createSequentialGroup()
                        .addComponent(labelFokusId_member, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelId_member)
                            .addComponent(inputId_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(panelMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labeDenda)
                            .addComponent(inputDenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelFokusDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelParentLayout = new javax.swing.GroupLayout(panelParent);
        panelParent.setLayout(panelParentLayout);
        panelParentLayout.setHorizontalGroup(
            panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelParentLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panelMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        panelParentLayout.setVerticalGroup(
            panelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParentLayout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelParent, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputId_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputId_memberActionPerformed
        // TODO add your handling code here:
        buttonCheckActionPerformed(evt);
    }//GEN-LAST:event_inputId_memberActionPerformed

    private void inputId_memberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputId_memberKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputId_memberKeyPressed

    private void inputDendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDendaActionPerformed

    private void buttonCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCheckActionPerformed
        // TODO add your handling code here:
        try {
            PinjamDao dao = PinjamDatabase.getPinjamDao();
            try {
                tableModel.setList(dao.getPinjam(inputId_member.getText()));
                tableModel.fireTableDataChanged();
                inisialisasi_tabel();
            } catch (PinjamException ex) {
                Logger.getLogger(PengembalianKasirView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PengembalianKasirView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonCheckActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void buttonUpdatePinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdatePinjamActionPerformed
        // TODO add your handling code here:
        pinjamController.updatePengembalianKasir(this);
        bukuController.updatePengembalianBukuKasir(this);
        buttonCheckActionPerformed(evt);
        inputId_member.setText(null);
        inputDenda.setText(null);
    }//GEN-LAST:event_buttonUpdatePinjamActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        // TODO add your handling code here:
        inputId_member.setText("");
        for (int i = tabelPinjam.getRowCount() - 1; i >= 0; i--) {
            tableModel.remove(i);
        }
        inisialisasi_tabel();
    }//GEN-LAST:event_buttonResetActionPerformed

    private void inputId_memberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputId_memberFocusGained
        // TODO add your handling code here:
        labelFokusId_member.setText("<html>Masukkan ID Member yang ingin mengembalikan buku, pastikan member memperlihatkan kartu membernya</html>");
        labelFokusDenda.setText("");
    }//GEN-LAST:event_inputId_memberFocusGained

    private void inputDendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputDendaFocusGained
        // TODO add your handling code here:
        labelFokusDenda.setText("<html>Perhatikan Tanggal Kembali setiap buku, masukkan nilai 0 jika tidak ada denda dan jika ada masukkan digit dendanya saja misal, 5000</html>");
        labelFokusId_member.setText("");
    }//GEN-LAST:event_inputDendaFocusGained

    private void buttonBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBack1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonBack1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private faraz.view.usu.Button buttonBack1;
    private faraz.view.usu.Button buttonBatal;
    private faraz.view.usu.Button buttonCheck;
    private faraz.view.usu.Button buttonReset;
    private faraz.view.usu.Button buttonUpdatePinjam;
    private faraz.view.usu.TextBox inputDenda;
    private faraz.view.usu.TextBox inputId_member;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel labeDenda;
    private javax.swing.JLabel labelFokusDenda;
    private javax.swing.JLabel labelFokusId_member;
    private javax.swing.JLabel labelId_member;
    private javax.swing.JPanel panelMain1;
    private faraz.view.usu.Panel panelParent;
    private javax.swing.JTable tabelPinjam;
    private faraz.view.usu.Toolbar toolbar;
    // End of variables declaration//GEN-END:variables

    public void inisialisasi_tabel() {
        tabelPinjam.setModel(tableModel);
    }

    @Override
    public void onChange(PinjamModel model) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void onInsert(Pinjam pinjam) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void onUpdate(Pinjam pinjam) {
        int index = tabelPinjam.getSelectedRow();
        tableModel.set(index, pinjam);
    }

    @Override
    public void onDelete() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        Pinjam model = tableModel.get(tabelPinjam.getSelectedRow());
        inputDenda.setText(model.getDenda() + "");
    }
}
